CREATE TABLE `imports` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`token` text,
	`token_hash` text NOT NULL,
	`status` text NOT NULL,
	`source_url` text,
	`home_url` text,
	`endpoint_url` text,
	`allow_http` integer DEFAULT 0 NOT NULL,
	`plugin_version` text,
	`protocol` integer,
	`wp_version` text,
	`php_version` text,
	`table_prefix` text,
	`multisite` integer,
	`blog_public` integer,
	`files_bytes` integer,
	`db_bytes` integer,
	`file_count` integer,
	`table_count` integer,
	`report` text,
	`warnings` text,
	`choices` text,
	`cursor` text,
	`staging_path` text,
	`site_id` integer,
	`server_id` integer,
	`job_id` integer,
	`last_error` text,
	`created_by` text,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	`connected_at` integer,
	`expires_at` integer,
	`started_at` integer,
	`pulled_at` integer,
	`imported_at` integer,
	`disconnected_at` integer,
	FOREIGN KEY (`site_id`) REFERENCES `sites`(`id`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (`server_id`) REFERENCES `servers`(`id`) ON UPDATE no action ON DELETE set null
);
--> statement-breakpoint
CREATE UNIQUE INDEX `imports_token_hash_idx` ON `imports` (`token_hash`);--> statement-breakpoint
CREATE INDEX `imports_status_idx` ON `imports` (`status`);--> statement-breakpoint
CREATE INDEX `imports_site_idx` ON `imports` (`site_id`);