/**
 * Writing the generated pages. Each is plain Markdown with front matter, and right below the
 * front matter one comment that names the script, its sources and the sha256 of everything
 * under that line:
 *
 *   <!-- generated by docs/site/scripts/gen-api.ts from panel/shared/apiDocs.ts; do not edit. sha256:… -->
 *
 * docs:map recomputes the hash, so a hand edit fails it, and the `check` job regenerates every
 * page and fails on a difference. The output is deterministic: same sources, same bytes.
 */
import fs from 'node:fs';
import path from 'node:path';
import { stringify } from 'yaml';
import { CONTENT_DIR, parseGenerated, repoRel, sha256, splitFrontMatter } from './pages.js';

export interface GeneratedPage {
  /** Path under src/content/docs, ending in .md. */
  path: string;
  title: string;
  description: string;
  order: number;
  /** Sidebar label, when it should differ from the title. */
  label?: string;
  /** Repository globs the page documents, for docs:map and docs-sync. */
  sources: string[];
  /** The Markdown below the header. */
  body: string;
}

export function renderPage(script: string, from: readonly string[], page: GeneratedPage): string {
  const frontMatter = stringify(
    {
      title: page.title,
      description: page.description,
      sidebar: page.label ? { order: page.order, label: page.label } : { order: page.order },
      sources: page.sources,
    },
    { lineWidth: 0 },
  );
  const body = `\n${page.body.trim()}\n`;
  const header = `<!-- generated by docs/site/scripts/${script} from ${from.join(', ')}; do not edit. sha256:${sha256(body)} -->`;
  return `---\n${frontMatter}---\n${header}\n${body}`;
}

/**
 * Write the pages, replacing the .mdx stub of each and, under `ownDir`, removing the pages this
 * script wrote before that it no longer writes. Returns the files written or removed.
 */
export function writePages(script: string, from: readonly string[], pages: GeneratedPage[], opts: { ownDir?: string } = {}): string[] {
  const changed: string[] = [];
  const wanted = new Set<string>();
  for (const page of pages) {
    const abs = path.join(CONTENT_DIR, page.path);
    wanted.add(abs);
    const next = renderPage(script, from, page);
    if (!fs.existsSync(abs) || fs.readFileSync(abs, 'utf8') !== next) {
      fs.mkdirSync(path.dirname(abs), { recursive: true });
      fs.writeFileSync(abs, next);
      changed.push(repoRel(abs));
    }
    const stub = abs.replace(/\.md$/, '.mdx');
    if (fs.existsSync(stub)) {
      fs.rmSync(stub);
      changed.push(`${repoRel(stub)} (stub removed)`);
    }
  }
  if (opts.ownDir) {
    const dir = path.join(CONTENT_DIR, opts.ownDir);
    for (const name of fs.existsSync(dir) ? fs.readdirSync(dir).sort() : []) {
      const abs = path.join(dir, name);
      if (!name.endsWith('.md') || wanted.has(abs)) continue;
      const content = splitFrontMatter(fs.readFileSync(abs, 'utf8'))?.content ?? '';
      if (parseGenerated(content)?.by === `docs/site/scripts/${script}`) {
        fs.rmSync(abs);
        changed.push(`${repoRel(abs)} (removed)`);
      }
    }
  }
  return changed;
}

/** Print what a generator did, the way every generator does. */
export function report(script: string, changed: string[], total: number): void {
  const what = changed.length === 0 ? 'up to date' : changed.join(', ');
  console.log(`${script}: ${total} page${total === 1 ? '' : 's'}, ${what}`);
}
