/**
 * The docs pages as the docs-signals scripts see them: every file under src/content/docs, its
 * front matter, slug, public URL and sidebar group, the code it says it documents (`sources:`),
 * and whether a generator wrote it. docs-map, docs-sync, sync-markers and the checks start here.
 */
import { createHash } from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { glob } from 'tinyglobby';
import { parse as parseYaml } from 'yaml';

export const SITE_DIR = path.resolve(import.meta.dirname, '../..');
export const REPO_ROOT = path.resolve(SITE_DIR, '../..');
export const CONTENT_DIR = path.join(SITE_DIR, 'src/content/docs');
/** The published site: `site` + `base` in astro.config.mjs. */
export const SITE_URL = 'https://wpl7.com/docs/';

/** Sidebar groups whose pages document a feature, and so must name the code they document. */
export const FEATURE_GROUPS = [
  'sites',
  'servers',
  'plugins',
  'backups',
  'mail',
  'security',
  'automations',
  'integrations',
  'panel',
] as const;

/** What the header of a generated page says: who wrote it, from what, and a hash of the body. */
export interface GeneratedHeader {
  /** `docs/site/scripts/gen-api.ts` */
  by: string;
  /** The source files, as the header lists them. */
  from: string;
  /** The hash the generator recorded. */
  hash: string;
  /** Everything below the header line: what the hash covers. */
  body: string;
}

export interface Page {
  /** The URL path under /docs/ without slashes at either end: `sites/create`; '' for the introduction. */
  slug: string;
  /** Repository-relative path of the page's file. */
  file: string;
  /** Absolute path of the page's file. */
  abs: string;
  /** Public URL. */
  url: string;
  /** The first folder, which is the sidebar group; '' for pages at the root. */
  group: string;
  title: string;
  description: string;
  /** `sources:` from the front matter: repository globs. */
  sources: string[];
  frontMatter: Record<string, unknown>;
  /** The text after the front matter. */
  content: string;
  /** Set when a generator wrote the page. */
  generated: GeneratedHeader | null;
  /** Problems reading the page itself (front matter that does not parse, sources that are not a list). */
  problems: string[];
}

export const toPosix = (p: string): string => p.split(path.sep).join('/');
export const repoRel = (abs: string): string => toPosix(path.relative(REPO_ROOT, abs));

export function sha256(text: string): string {
  return createHash('sha256').update(text, 'utf8').digest('hex');
}

/** True when the module at `importMetaUrl` is the script node was started with. */
export function isMain(importMetaUrl: string): boolean {
  const entry = process.argv[1];
  return entry !== undefined && pathToFileURL(path.resolve(entry)).href === importMetaUrl;
}

/** `sites/create.mdx` -> `sites/create`; `index.mdx` -> ''; `integrations/api-reference/index.md` -> `integrations/api-reference`. */
export function slugOf(relToContent: string): string {
  const noExt = toPosix(relToContent).replace(/\.(md|mdx)$/, '');
  if (noExt === 'index') return '';
  return noExt.replace(/\/index$/, '');
}

export function urlOf(slug: string): string {
  return slug === '' ? SITE_URL : `${SITE_URL}${slug}/`;
}

/** The first line of a generated page's body, right after the front matter. */
export const GENERATED_RE = /^<!-- generated by (\S+) from (.+?); do not edit\. sha256:([0-9a-f]{64}) -->\n/;

export function parseGenerated(content: string): GeneratedHeader | null {
  const match = GENERATED_RE.exec(content);
  if (!match) return null;
  return { by: match[1]!, from: match[2]!, hash: match[3]!, body: content.slice(match[0].length) };
}

/** Split a page into its front matter (unparsed) and what follows it. */
export function splitFrontMatter(text: string): { yaml: string; content: string } | null {
  const normalized = text.replace(/\r\n/g, '\n');
  if (!normalized.startsWith('---\n')) return null;
  const end = normalized.indexOf('\n---', 4);
  if (end === -1) return null;
  const afterFence = normalized.indexOf('\n', end + 4);
  return {
    yaml: normalized.slice(4, end + 1),
    content: afterFence === -1 ? '' : normalized.slice(afterFence + 1),
  };
}

export function readPage(abs: string): Page {
  const relToContent = toPosix(path.relative(CONTENT_DIR, abs));
  const slug = slugOf(relToContent);
  const problems: string[] = [];
  const text = fs.readFileSync(abs, 'utf8');
  const split = splitFrontMatter(text);
  let frontMatter: Record<string, unknown> = {};
  if (!split) {
    problems.push('has no front matter');
  } else {
    try {
      const parsed: unknown = parseYaml(split.yaml);
      if (parsed && typeof parsed === 'object' && !Array.isArray(parsed)) frontMatter = parsed as Record<string, unknown>;
      else problems.push('front matter is not a mapping');
    } catch (err) {
      problems.push(`front matter does not parse: ${err instanceof Error ? err.message : String(err)}`);
    }
  }
  let sources: string[] = [];
  const raw = frontMatter.sources;
  if (raw !== undefined && raw !== null) {
    if (Array.isArray(raw) && raw.every((s) => typeof s === 'string')) sources = raw as string[];
    else problems.push('sources: is not a list of globs');
  }
  const content = split?.content ?? '';
  return {
    slug,
    file: repoRel(abs),
    abs,
    url: urlOf(slug),
    group: relToContent.includes('/') ? relToContent.split('/')[0]! : '',
    title: typeof frontMatter.title === 'string' ? frontMatter.title : slug || 'Introduction',
    description: typeof frontMatter.description === 'string' ? frontMatter.description : '',
    sources,
    frontMatter,
    content,
    generated: parseGenerated(content),
    problems,
  };
}

/** Every page, sorted by file path. */
export async function listPages(): Promise<Page[]> {
  const files = await glob('**/*.{md,mdx}', { cwd: CONTENT_DIR, absolute: true });
  return files.sort().map(readPage);
}

/** What `sources:` globs resolve against: the repository, never its dependencies or build output. */
export const SOURCE_IGNORE = ['**/node_modules/**', '**/dist/**', '.git/**', 'docs/site/.astro/**'];

/** Each glob with the repository files it matches, sorted. */
export async function resolveGlobs(globs: readonly string[]): Promise<Map<string, string[]>> {
  const out = new Map<string, string[]>();
  for (const pattern of globs) {
    if (out.has(pattern)) continue;
    const files = await glob(pattern, { cwd: REPO_ROOT, dot: true, ignore: SOURCE_IGNORE, expandDirectories: false });
    out.set(pattern, files.map(toPosix).sort());
  }
  return out;
}
